name: shoe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  supabase_flutter: ^2.12.0
  hive_flutter: ^1.1.0
  google_sign_in: ^6.1.5
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  cherry_toast: ^1.13.0
  dart_either: ^2.0.0
  shimmer_animation: ^2.2.2+1
  cached_network_image: ^3.4.1
  sqflite: ^2.3.3
  another_carousel_pro: ^1.0.2
  animated_bottom_navigation_bar:  ^1.4.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.3.3

dev_dependencies:
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/splicon3.png   # splash image
  fullscreen: true

  android_12:
    image: assets/images/splicon3.png
    icon_background_color: #2b8065

  branding: assets/images/spltext.png   # <-- bottom text image

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splicon2.png"   # launcher icon

flutter:
  uses-material-design: true

  assets:
    - assets/images/
