name: shoe
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/splicon3.png   # splash image
  fullscreen: true

  android_12:
    image: assets/images/splicon3.png
    icon_background_color: #2b8065

  branding: assets/images/spltext.png   # <-- bottom text image

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splicon2.png"   # launcher icon

flutter:
  uses-material-design: true

  assets:
    - assets/images/
